### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by egarza** [BlitzKraig/fvtt-BetterAmbientLoop#2] opened 2020-08-21 02:25 UTC
I was using the Better Ambient Loop module and I had a general problem with sounds. The problem was, I inserted ambient sound using an mp3 in my data path. If I closed Foundry and open again, the sound did not play in token mode. If I open the settings, the path says it's incorrect. I think it is reading the short version of the path.
This problem goes away after disabling the module.

I'm using a MacBook Pro.

**Comment by BlitzKraig** [comment] 2020-08-21 13:20
Hi, thanks for the feedback. What version of Foundry are you running?

**Comment by egarza** [comment] 2020-08-21 16:48
Version Core 0.6.5

**Comment by BlitzKraig** [comment] 2020-08-21 19:40
Hi egarza,
I've just tested this and I'm unable to reproduce.
I tried refreshing foundry & completely closing the server, and both worked fine.
Tested with mp3 and ogg.

Do you have any more information? A screenshot of the working config & the broken config may help.

Feel free to DM me on Discord too.

**Closed as completed** 2020-10-04 12:42 UTC
